In [ ]:
#Numpy is python library used for working  arrays


In [2]:
! pip install numpy



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np


In [8]:
x=np.array([1,3,2,4,5,8,9.5,12])
print(type(x))

<class 'numpy.ndarray'>


In [10]:
x=np.array([1,3,2,4,5,8,95,12])
print(type(x))

<class 'numpy.ndarray'>


In [22]:
#arrange method 
a=np.arange(10,-4,-20)
print(a)

[10]


In [24]:
#random number[)
a=np.random.random(size=(4,3))
print(a)

[[0.57655482 0.06954261 0.36019629]
 [0.45260317 0.59412806 0.01287268]
 [0.41660274 0.20791724 0.9657414 ]
 [0.37121902 0.99612005 0.51184672]]


In [12]:
import numpy as np


In [18]:
x1=np.random.randint(50,size=6)
x2=np.random.randint(500,size=6)
print(x1)
print (x2)

[22 37 32  5 36  5]
[ 84 132 413 254 426 426]


In [ ]:
arr=np.array(11)
print(arr)                            #zero dimension 
print("Dimensions:",arr.ndim)

11
Dimensions: 0


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)                        #one dimension 
print("Dimensions:",arr.ndim)

[1 2 3 4 5]
Dimensions: 1


In [ ]:
data=([[1,2,3,4,5],[1,5,55,78,1]])
arr=np.array(data)                  #two dimensions 
print(arr)
print("Dimensions:",arr.ndim)



[[ 1  2  3  4  5]
 [ 1  5 55 78  1]]
Dimensions: 2


In [ ]:
data=([[[1,2,3,4,5],[1,5,55,78,1],[8,6,9,12,78]]])
arr=np.array(data)                     #three dimensions
print(arr)
print("Dimensions:",arr.ndim)

[[[ 1  2  3  4  5]
  [ 1  5 55 78  1]
  [ 8  6  9 12 78]]]
Dimensions: 3


In [36]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(24).reshape(2,4,3)
print(a1,a2,a3)

[0 1 2 3 4 5 6 7 8 9] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [12]:
import numpy as np


In [13]:
a1=np.arange(10)
print(a1[::]) 
print(a1[::-1])
print(a1[2::2])


[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6 8]


In [41]:
a2 = np.arange(12).reshape(3, 4)

print(a2[1::, ::2])   # rows from index 1, columns with step 2
print(a2[0, :])       # first row
print(a2[:, 0])       # first column
print(a2[1:, 1:])     # rows from index 1, columns from index 1
print(a2[::2, ::2])   # every other row and column
print(a2)





[[ 4  6]
 [ 8 10]]
[0 1 2 3]
[0 4 8]
[[ 5  6  7]
 [ 9 10 11]]
[[ 0  2]
 [ 8 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
a3=np.arange(24).reshape(2,4,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
print(a3[1,1::2,::2])
print(a3[0])
print(a3[0,0])
print(a3[1,:3])
print(a3[:,::3,::2])
print(a3[::-2])


[[15 17]
 [21 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[12 13 14]
 [15 16 17]
 [18 19 20]]
[[[ 0  2]
  [ 9 11]]

 [[12 14]
  [21 23]]]


In [75]:
a1=np.array([1,2,3,5])
a2=np.array([1.2,8.5,7,8])
print(a1.dtype)
print(a2.dtype)
print(a1.itemsize)
print(a2.itemsize)
print(a1.nbytes)
print(a2.nbytes)


int64
float64
8
8
32
32


In [76]:
a1=np.array([1,2,3,5])
a2=np.array([1.2,8.5,7,8])
print(a1.ndim)
print(a2.ndim)
print(a1.shape)
print(a2.shape)
print(a1.size)
print(a2.size)


1
1
(4,)
(4,)
4
4


In [77]:
#np.zeroes
print(np.zeros(10))
print()
print(np.zeros((3,6),dtype="int"))
print()
print(np.zeros((2,3,2)))
print()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]



In [78]:
#identity matrics
np.identity(4,dtype="int32")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [ ]:
#Arthematical operation using numpy
#Scalar vector 


In [5]:
import numpy as np
a1=np.array([1,2,5,9])
b1=np.array([2,5,9,7])
print(a1)
print(b1)
print(a1+5)
print(b1-1)
print(a1*3)
print(b1*4)
print(a1%2)
print(a1//2)

[1 2 5 9]
[2 5 9 7]
[ 6  7 10 14]
[1 4 8 6]
[ 3  6 15 27]
[ 8 20 36 28]
[1 0 1 1]
[0 1 2 4]


In [ ]:
#vector array creation 

In [7]:
print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)
print(a1//b1)
print(a1**b1)
print(a1%b1)

[ 3  7 14 16]
[-1 -3 -4  2]
[ 2 10 45 63]
[0.5        0.4        0.55555556 1.28571429]
[0 0 0 1]
[      1      32 1953125 4782969]
[1 2 5 2]


In [12]:
#Dot product 
a1=np.array([5,8,9,10])
a2=np.array([5,3,8,9])

print(np.dot(a1,a2))

211


In [17]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12).reshape(4,3)
print(np.dot(a1,a2))


[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


In [27]:
a1=np.arange(12).reshape(3,4)
print(np.mean(a1))
print(np.mean(a1,axis=0))
print(np.mean(a1,axis=1))
print()
print()
print(np.min(a1))
print(np.min(a1,axis=0))
print(np.min(a1,axis=1))
print()
print()
print(np.max(a1))
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))
print()
print()
print(np.var(a1))
print(np.var(a1,axis=0))
print(np.var(a1,axis=1))
print()
print()
print(np.sum(a1))
print(np.sum(a1,axis=0))
print(np.sum(a1,axis=1))


5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


0
[0 1 2 3]
[0 4 8]


11
[ 8  9 10 11]
[ 3  7 11]


11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]


66
[12 15 18 21]
[ 6 22 38]


In [ ]:
a1=np.arange(12).reshape(3,4)
print(np.mean(a1))
print(np.mean(a1,axis=0))
print(np.mean(a1,axis=1))

In [ ]:
a1=np.arange(12).reshape(3,4)
print(np.min(a1))
print(np.min(a1,axis=0))
print(np.min(a1,axis=1))

In [30]:
a1=np.arange(12).reshape(3,4)
print(np.max(a1))
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))

11
[ 8  9 10 11]
[ 3  7 11]


In [29]:
a1=np.arange(12).reshape(3,4)
print(np.var(a1))
print(np.var(a1,axis=0))
print(np.var(a1,axis=1))

11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]


In [28]:
a1=np.arange(12).reshape(3,4)
print(np.sum(a1))
print(np.sum(a1,axis=0))
print(np.sum(a1,axis=1))

66
[12 15 18 21]
[ 6 22 38]


In [36]:
#percentile in numpy
import numpy as np
x=np.arange(12).reshape(3,4)
p25=np.percentile(x,25)
p50=np.percentile(x,50)
p75=np.percentile(x,75)
p100=np.percentile(x,100)
print()
print("25 percentile",p25)
print("50 percentile",p50)
print("75 percentile",p75)
print("100 percentile",p100)




25 percentile 2.75
50 percentile 5.5
75 percentile 8.25
100 percentile 11.0


In [37]:
#iterating through an array
a1=np.array([2,4,5,7,8,4,1,5,6])
for i in a1:
    print(i,end="")

245784156

In [42]:
#2d array
a2=np.arange(20).reshape(4,5)
for i in a2:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [41]:
a2=np.arange(20).reshape(4,5)
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
#2d array
a2=np.arange(20).reshape(4,5)
print(a2)
a2[0]
for i in range()
    print(i)
    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
